### PR TITLE
Prepare for release 2.2.2

### PR DESCRIPTION
**Pull request by wilsonwu**
Prepare for release Nacos Server 2.2.2

### CODE REVIEW

**Comment by wilsonwu** [comment]
@paderlol please help to review and let release the latest docker image :)

**Comment by paderlol** [comment]
Plz update the version in  .env  file

**Comment by paderlol** [comment]
https://github.com/nacos-group/nacos-docker/blob/master/example/.env 
Please update the NACOS_VERSION＝v2.2.2

@wilsonwu

**Comment by wilsonwu** [comment]
> https://github.com/nacos-group/nacos-docker/blob/master/example/.env Please update the NACOS_VERSION＝v2.2.2
> 
> @wilsonwu

Done, remembered this next time :)

**Pull request merged**
