### PR TITLE
Update README_ZH.md

### PR DESCRIPTION
**Pull request by peiel**
fix: 修改错别字

### CODE REVIEW

**Comment by wilsonwu** [comment]
Thansks for you fix, let's review @paderlol

**Comment by wilsonwu** [comment]
@peiel seems there are conflicts here, please try to rebase the main branch, thanks!

**Comment by peiel** [comment]
The code conflicts have been resolved.

**Comment by wilsonwu** [comment]
LGTM.

@peiel sorry for this, no stable reviewer this repo, and I don't have permission for approve PR.

**Comment by wilsonwu** [comment]
heart breaking for this said story.

**Pull request closed without merging**
