### PR TITLE
Prepare to release 2.2.3

### PR DESCRIPTION
**Pull request by wilsonwu**
Prepare to release Nacos 2.2.3

### CODE REVIEW

**Comment by wilsonwu** [comment]
@paderlol please help to release 2.2.3, thank you!

**Comment by wilsonwu** [comment]
@paderlol could you please help to trigger the release process for 2.2.3?

**Review by KomachiSion — APPROVED** [review]

**Comment by wuai1024** [comment]
这个不是同步发布版本的啊？

**Comment by wilsonwu** [comment]
> 这个不是同步发布版本的啊？

是的，需要人工干预，更新了这些内容后还是要人工触发版本发布。

**Comment by wuai1024** [comment]
这过去好几天了，莫不是忘了啊？

**Comment by wilsonwu** [comment]
@KomachiSion could someone else can help to triger the release? @paderlol not at here more than a month.

**Comment by wilsonwu** [comment]
> We don't have to change the version in the Dockerfile every time we release a new version of Nacos, we can just create a new tag and draft a new Release if there are no changes. Once you have done this, we will automatically trigger **Github Action** to build the image and upload it to the **Docker Hub**. @wilsonwu

Got it, understood now, thanks for the expenations.

**Pull request merged**
