### PR TITLE
修复版本号不对导致无法拉取对应的tag镜像

### PR DESCRIPTION
**Pull request by jingjianqian**

### CODE REVIEW

**Comment by wilsonwu** [comment]
Please close this PR, the Nacos jar verison is x.y.z, without prefix v, thanks for your contribution.
image

**Comment by HZMarico** [comment]
image


image

**Comment by jingjianqian** [comment]
image
你的tag还是不对，没更新对吧

**Comment by jingjianqian** [comment]
image

**Comment by paderlol** [comment]
The tag issue has been fixed

**Comment by paderlol** [comment]
The version number has been fixed, but I don't understand why you have to change the SQL script acquisition to local, this will increase the cost of maintaining our scripts, whenever the script(Nacos) has changed, we will have to release it again.

**Comment by paderlol** [comment]
已修复,不再合并,另外脚本保持从Nacos官方项目下载是为了避免数据库变更后,需要再次同步维护

**Pull request closed without merging**
